### ISSUE TITLE
Frontend Design Implementation

### ISSUE THREAD

**Issue by awright** [hotosm/visualize-change#11]
Beta versions of frontend rendering and interface to be prepared for testing. Deliverables include:

- [ ] #8 Beta release of the API (rendering)
- [ ] #9 Beta version of the frontend UI
- [ ] #10 Alpha Release test version

As written in the proposal as Beta Versionl: 
"Beta version will include polished fronted UI, fixed backend bugs and possible improvements
for UX flow. We will also focus on adding email notification system, and handling edge cases.
Beta version should be tested."
