### ISSUE TITLE
Project Timeline

### ISSUE THREAD

**Issue by szymonkaliski** [hotosm/visualize-change#29]
**To be updated as we go.**

Latest info from: 2018-03-08

**What already is working:**

- [x] tabs switching on sidebar
- [x] searching map
- [x] zoom in/out
- [x] switching styles of roads/buildings
- [x] working export to video file (just map view exported, like we have in Gunung Agung animation examples)

**What we can get working on monday (2018-03-12):**

- [x] bit "nicer" ui (margins, element sizes etc. - not touching colours and "bigger" things until we get more feedback from you)
- [x] date buttons working (connected to "play" and what's visible on map)
- [x] bottom play bar working (connected with dates and bottom right corner date)
- [x] better "style" options, and background map layer switching
- [x] button to hide sidebar behind left part of the screen, and show it again
- [x] the "describe" can be filled out, but since we don't have "url sharing" it's not going to do anything yet
- [x] popup/toaster/some other visual way of showing user that zoom levels 0-11 are not supported
- [x] all of the above live on our test server
- [x] proposed timeline for next week or so (based on what we have on monday, and what we feel is a good next step)

**What would be the possible next steps after that (not in any specific order - tbd):**

- "proper" design (colors, button styles, etc... - waiting for feedback on issue #27)
- "share modal" - all the options we need, and nicer layout
- "shared" url view (sharing by link, with sidebar filled with data - slide 6)
- "fullscreen" button in "create" mode, and in "shared" url
- "preview" sidebar button(? - or some other solution to "preview" the "url share" view)
- adding slide 1 (intro screen)
- figuring out what "learn" and "create" buttons should do
- figuring out if / how we want to overlay dates on video and gif exports
- localisation of the app

**Comment by szymonkaliski** [comment]
Everything from previous post is done and live on our test server; the buttons that are not currently working are blocked.

**For next week (2018-03-19) our plan is to:**

- [ ] create "share url" view (the url that you can open and see the animation with description)

This is bit bigger task, and requires:

- [ ] db setup for storing the data
- [ ] router for url matching (view/edit)
- [ ] updates to "share" modal window

**Comment by awright** [comment]
@szymonkaliski - Thanks so much for the timeline. Can you share the link we should be looking at?

Some questions:

- From our meeting where we discussed the revise UI workflow #27 we also noted that date selection was complete. Is this accurate?
- You say certain work can be completed by **Moday 03-08-2018** are you referring to today: 03-12-2018?
- The majority of HOT feedback on the UI will come after we finish functionality
- "the "describe" can be filled out, but since we don't have "url sharing" it's not going to do anything yet" To summarize our meeting, the Describe Button will provide context for users and summarize choices made in the other 3 tabs.
- "proposed timeline for next week or so (based on what we have on Monday, and what we feel is a good next step)" should we expect another timeline of outstanding items (below) by Monday 03-19?
- "What would be the possible next steps after that (not in any specific order - tbd):" What dates do you refer to here?
- ""share modal" - all the options we need, and nicer layout" What do you mean here? I thought we would have a link and a download?
- "figuring out what "learn" and "create" buttons should do" Learn will be some version of a UX documentation but Create goes to the pages we have been looking at. "Create" means "create animation: Does that need further clarification?
- "figuring out if / how we want to overlay dates on video and gif exports" I think we resolved this for the time being and do not need a date overlay. The date needs to be more prominent in the URL and create animation view. Does this need further clarification?
- What do you mean by localization of the map?
- " create "share url" view (the url that you can open and see the animation with description)" Why is this blocked? Can you further explain?

Let's talk about these larger issues at our next meetings cc @smit1678 
- "db setup for storing the data
-  router for url matching (view/edit)
 - updates to "share" modal window"

**Comment by awright** [comment]
Also, we are looking at a larger timeline of functionality end of March. Want to keep the big picture in our minds. Thanks! cc @szymonkaliski

**Comment by szymonkaliski** [comment]
> Can you share the link we should be looking at?

I'll share the link on slack so to not expose the server to the public yet.

> From our meeting where we discussed the revise UI workflow #27 we also noted that date selection was complete. Is this accurate?

Yes.

> You say certain work can be completed by Moday 03-08-2018 are you referring to today: 03-12-2018?

Yes, my mistake, this is fixed. Thanks!

> "proposed timeline for next week or so (based on what we have on Monday, and what we feel is a good next step)" should we expect another timeline of outstanding items (below) by Monday 03-19?

I plan on updating "next steps" for about a week in advance, so now we have a plan for this week, with "soft" deadline around next Monday.

> "What would be the possible next steps after that (not in any specific order - tbd):" What dates do you refer to here?

No dates for this, we need to figure out it as we go I think.

> ""share modal" - all the options we need, and nicer layout" What do you mean here? I thought we would have a link and a download?

There's few options that need to go into that modal, so we need to just make it look bit nicer than the way it looks like now in the demo.

> "figuring out what "learn" and "create" buttons should do" Learn will be some version of a UX documentation but Create goes to the pages we have been looking at. "Create" means "create animation: Does that need further clarification?

Ok, let's implement the workflow one-by-one, we are first implementing the "main tool view", and now the "share url view", so let's figure out the intro page and "create" button after that...

> "figuring out if / how we want to overlay dates on video and gif exports" I think we resolved this for the time being and do not need a date overlay. The date needs to be more prominent in the URL and create animation view. Does this need further clarification?

No, I don't think so.

> What do you mean by localization of the map?

Different languages :)

> " create "share url" view (the url that you can open and see the animation with description)" Why is this blocked? Can you further explain?

Not blocked, we are working on this in this week iteration.

**Comment by awright** [comment]
I will go over this in more detail later today. Poke me if there is
anything in particular that is blocking you more immediately. Thanks!

**Comment by awright** [comment]
I'll do inline to your inline. ;) 

> > Can you share the link we should be looking at?
> 
>I'll share the link on slack so to not expose the server to the public yet.

Great. 

> >From our meeting where we discussed the revise UI workflow #27 we also noted that date selection was complete. Is this accurate?
> 
> Yes.

👍 
>> You say certain work can be completed by Moday 03-08-2018 are you referring to today: 03-12-2018?
> 
> Yes, my mistake, this is fixed. Thanks!

👍  
> >"proposed timeline for next week or so (based on what we have on Monday, and what we feel is a good next step)" should we expect another timeline of outstanding items (below) by Monday 03-19?
> 
> I plan on updating "next steps" for about a week in advance, so now we have a plan for this week, with "soft" deadline around next Monday.

👍 
> 
>> "What would be the possible next steps after that (not in any specific order - tbd):" What dates do you refer to here?
> 
> No dates for this, we need to figure out it as we go I think.

OK.

>> ""share modal" - all the options we need, and nicer layout" What do you mean here? I thought we would have a link and a download?
> 
> There's few options that need to go into that modal, so we need to just make it look bit nicer than the way it looks like now in the demo.

Cool. We can confirm that that in near term priorities, we will have a functional share button that allows for downloading the animation and sending a URL for viewing? This would high priority. 

> 
>> "figuring out what "learn" and "create" buttons should do" Learn will be some version of a UX documentation but Create goes to the pages we have been looking at. "Create" means "create animation: Does that need further clarification?
> 
> Ok, let's implement the workflow one-by-one, we are first implementing the "main tool view", and now the "share url view", so let's figure out the intro page and "create" button after that...

Not sure what you are suggesting here.. but the first page of this workflow would be what someone sees when they click the "Create" button. We may further refine that in the future... and we should probably confirm that tomorrow with @smit1678 - but this is what I was initially seeing. 
> 
>> "figuring out if / how we want to overlay dates on video and gif exports" I think we resolved this for the time being and do not need a date overlay. The date needs to be more prominent in the URL and create animation view. Does this need further clarification?
> 
> No, I don't think so.

Great. So we will table a date overlay but will think about how we can make the current date information clearer. 
> 
> What do you mean by localization of the map?
> 
> Different languages :)

Cool. We can definitely table this for the immediate functionality. 
> 
> " create "share url" view (the url that you can open and see the animation with description)" Why is this blocked? Can you further explain?
> 
> Not blocked, we are working on this in this week iteration.

Yay! ;)

**Comment by szymonkaliski** [comment]
> We can confirm that that in near term priorities, we will have a functional share button that allows for downloading the animation and sending a URL for viewing? This would high priority.

Yes, generating animation (mp4/gif) with download link via email is already working, and we are currently implementing "share url".

> Not sure what you are suggesting here.. but the first page of this workflow would be what someone sees when they click the "Create" button. We may further refine that in the future... and we should probably confirm that tomorrow with @smit1678 - but this is what I was initially seeing.

Yes sure, what I mean is we will first implement share url view (our current priority) and then work on implementing this.

**Comment by szymonkaliski** [comment]
Recent update is live on our dev server, bringing:

- share / view mode
- ability to "share url" to animation
- saving configs into DB
- updated "share" modal

**For next week iteration (2018-03-26), we will implement:**

- [ ] add fullscreen button to "create" and "share" URLs
- [ ] add "slide 1" from the doc (intro screen) (https://github.com/hotosm/visualize-change/issues/27#issue-300410995)
- [ ] create url and page for tutorial/learn (content to be provided by HOT)

**Comment by szymonkaliski** [comment]
Recent update is now live on test server bringing:

- fullscreen button
- intro screen
- url for tutorial/learn
- very initial UI styling (colors)

**For next Tuesday (Monday is holiday here) (2018-04-03) we plan on:**

- fixing bugs that Iyan stumbled upon (holding off with UX fixes until we chat about it together):
  - [ ] problematic "playing" on slow internet
  - [ ] roads/buildings layer disappearing
  - [ ] searching on map not brining user to proper zoom level
  - [ ] random problem with mp4/gif rendering engine crashing

- some light cleanup work:
  - [ ] adding logging to frontend `serve.js` and `forever` for restarts if it crashes

- more ui work
  - [ ] more work on styling (colors, fonts, element sizes, etc...) to match http://www-dev.hotosm.org/
  - [ ] adding info about "exported video will be send to you via email when it's finished" in the "share" modal
  - [ ] adding width/height configuration for mp4/gif export
  - [ ] asking user to save when leaving page with unsaved changes

**Comment by szymonkaliski** [comment]
Yes, let's add "new" button for this week iteration, good idea!

**Comment by szymonkaliski** [comment]
New version is up on our test server bringing all the updates from previous comment: https://github.com/hotosm/visualize-change/issues/29#issuecomment-376246290

Now, as for next steps, we need to discuss together:

- we will make some UX fixes proposals based on my post in https://github.com/hotosm/visualize-change/issues/32#issuecomment-378282523
- we should discuss those as a group and move forward afterwards
- we should also discuss the need to auto-remove mp4/gif exports from server after some time (30 days?) to save space

We also want to work on two smaller things:

- [ ] block re-rendering exact same animation twice (to save CPU) - this only matters for mp4/gif exports
- [ ] check possible problems with rendering map (in browser) on big screens - maybe, possibly, a bug in mapboxgl...

**Comment by szymonkaliski** [comment]
Updated project timeline based on meeting: https://github.com/hotosm/visualize-change/issues/36


By **2018-04-11**:

- UX:
  - [ ] implement UX updates from https://github.com/hotosm/visualize-change/issues/32#issuecomment-378571531
    - [ ] updated header
    - [ ] sidebar without tabs
    - [ ] help menus/tutorial (autostarts on first visit)
    - [ ] map legend with roads/buildings and zoom scale
  - [ ] add popup info after mp4/gif render is triggered
  - [ ] make "new" button reset state of the current view to default one
  - [ ] make map zoomed-out on start by default (and after clicking "new" button)
  - [ ] remove search bar and zoom in/out when in "view" mode
  - [ ] remove the confusing triangle under "+"/"-" buttons on map view 
  - [ ] block "save" button when no changes were made
  - [ ] remove "HOT" from text near logo (just "Visualize Change" - also make sure "Visualize" is spelled same way throughout the app)
  - [ ] allow user to control speed of animation in "view"/"edit" modes (another config setting below "date span", this should be connected to FPS in share view, so the speed of web animation is at least bit aligned with mp4 exported speed)
- bugfixes:
  - [ ] block re-rendering exact same animation twice (to save CPU) - this only matters for mp4/gif exports
  - [x] check possible problems with rendering map (in browser) on big screens - maybe, possibly, a bug in mapboxgl... ("fixed" with workaround for now)
  - [ ] figure out problems with mp4/gif rendering sometimes erroring out

By **2018-04-16**:

- [ ] implementing "Nate's view", discussion here: https://github.com/hotosm/visualize-change/issues/32#issuecomment-378641371

After **2018-04-16**:

- tests & bugfixes
- possibly adding "learn" page content, or removing it, based on how the help icons work in the app
- documentation improvements (@awright - please share what you feel is missing from github README file here)

**Comment by awright** [comment]
looks good @szymon. at the moment i think the readme file is good and will
continue to review.

**Comment by szymonkaliski** [comment]
Ok, so the UX/UI work is live on our test server, we are working for Monday with Nate's view implemented and some bugfixes.

**Comment by awright** [comment]
Great. We can further review tomorrow at the meeting.

**Comment by awright** [comment]
awesome work! thanks @szymonkaliski for the update. i look forward to reviewing everything! can you explain -- from a user experience perspective -- what the following means?  

> we can't get map to reliably filter with overzoom generated by mapbogxl, we created an issue on mapbogxl github and waiting for fix, in the meantime, as a workaround, we blocked zoom level to be 12.

regarding the timeout - are you suggesting that we don't provide the option for a mp4/gif in certain instances? again, a description of this note from a user POV would be helpful. thanks!

**Comment by szymonkaliski** [comment]
> > awesome work! thanks @szymonkaliski for the update. i look forward to reviewing everything! can you explain -- from a user experience perspective -- what the following means?
>
> we can't get map to reliably filter with overzoom generated by mapbogxl, we created an issue on mapbogxl github and waiting for fix, in the meantime, as a workaround, we blocked zoom level to be 12.

The bug is described here: https://github.com/mapbox/mapbox-gl-js/issues/6515 let me know if that helps. For now the map is locked to max zoom of level 12, which "fixes" it.

> regarding the timeout - are you suggesting that we don't provide the option for a mp4/gif in certain instances? again, a description of this note from a user POV would be helpful. thanks!

What I mean is: now, when user renders mp4, it stays on the server forever (taking up space). We discussed briefly, some weeks ago, an idea to remove the mp4 files from the server after week/month/? that would free up the space. From user perspective the only change is, that after generating mp4/gif file, there's some "time window" where the file is available, and from our perspective, potentially, this saves hard drive space on the server.

**Comment by awright** [comment]
Let’s review the first issue at tomorrow’s meeting but I do agree that a
timeout for the mo4/gif makes sense. We will simply add that in the
instructions.

Let us say the file is available for 2 days. Chime in if anyone suggests
otherwise.

**Comment by szymonkaliski** [comment]
We are at the final week where we can do anything, and I really would advise against doing any big changes, as this might lead to bugs. We were hoping to focus on bugfixing this week, and if we work on more features, we just have to have this in mind, that they won't be battle tested.

Combining all the requests from different issues, here's what we can do:

- [ ] remove the landing page 
- [ ] rename "simple" -> "basic" tab
- [ ] remove "theme" & "title" from basic
- [ ] add more whitespace between title and menu options
- [ ] zoom in to where the person is on start (geocoded, zoom level 12)
- [ ] make simple / advanced tab - styled as navbar buttons
- [ ] describe -> add "location" below "name/title" and copy search from it (also add to "view" mode)
- [ ] describe -> rename "name" to "title"
- [ ] overlay loading spinner on top of map and make it bigger
- [ ] add "last year" to the simple dropdown options
- [ ] put "play button" in the sidebar (https://github.com/hotosm/visualize-change/issues/39#issuecomment-382460116)
- [ ] add yearly and monthly intervals to the tool
- [ ] updated "help"/"tutorial" texts (to be provided by HOT!)
- [ ] make date more prominent on the bottom bar
- [ ] add help section about bottom bar (play/date/etc) to the tutorial so users are less confused about it
- [ ] look into video renderer bugs, but not sure if we can fix them with all the other work

And finally, I'll prepare "future work" README section with possible future work.

I can't promise we will have everything before Wednesday's meeting, but we will have all the points by Fridays deadline.

After the deadline, we can do some basic bugfixing during 1-2 weeeks after the project, but for any new features or additional changes we will have to discuss new contract.

**Comment by awright** [comment]
Sounds great Szymon. I know there will be further discussions but this is a
great summary of where we are and what we want to complete by next week.
Thanks!

**Comment by szymonkaliski** [comment]
Just pushed update to our test server bringing few behind-the-scenes updates:

- speed up for re-rendering the same exported video
- fixed the selectable date spans to render at most 30 frames (otherwise it hogs our server, if we had better one, we could potentially render longer/more detailed exports)
- updated "speed" slider with more options
- fixed behaviour when video rendering crashes
- additional mp4/gif rendering bugfixes

We're working on the UI updates to be pushed by Friday's deadline.

**Comment by awright** [comment]
for the about page see #45 Help Prompts

**Comment by szymonkaliski** [comment]
Last update is up on the test server and on github!

We've added everything besides:

- we can't really access the search bar (it's coming from mapboxgl), so we have additional location field but it has to be filled out by hand
- instead of duplicating play button somewhere in the sidebar, we made it more prominent in the bottom bar, and added help menu next to it

I've also added possible future work to the README file.

🎉

**Comment by szymonkaliski** [comment]
Last changes are up on the test server, including as discussed:

- configurable interval step size: https://github.com/hotosm/visualize-change/blob/master/frontend/src/constans/index.js#L153 (this is concerned only for production setup / deployment)
- bigger loading spinner
- play button is disabled while the tiles are loading
- added new "learn" page
- added links to bottom left sidebar items (linking to HOT website and contributors on github)
- updated page window title to "HOT Visualize Change"
- fixed bug with sharing/rendering unsaved animation (https://github.com/hotosm/visualize-change/issues/46)

**Comment by szymonkaliski** [comment]
@smit1678 @awright - all the bugs are fixed now:

- [x] https://github.com/hotosm/visualize-change/issues/47
- [x] https://github.com/hotosm/visualize-change/issues/48
- [x] https://github.com/hotosm/visualize-change/issues/49
- [x] https://github.com/hotosm/visualize-change/issues/50
- [x] https://github.com/hotosm/visualize-change/issues/51
- [x] minor fullscreen issues

**Our test server is updated as well.**
